import { leadingEmoji } from './emoji';
import { normalizeLabel } from './skillCatalog';

const EXACT_EMOJI: Record<string, string> = {
  electrician: '⚡',
  plumber: '🔧',
  carpenter: '🪚',
  painter: '🎨',
  cleaner: '🧹',
  'home cleaning': '🧹',
  'deep cleaning': '✨',
  nurse: '💉',
  'doctor home visit': '👨‍⚕️',
  physiotherapist: '🦴',
  'lab technician': '🧪',
  'home tutor': '📚',
  'music teacher': '🎵',
  'dance teacher': '💃',
  'yoga trainer': '🧘',
  'gym trainer': '🏋️',
  'language tutor': '🗣️',
  'cab driver': '🚕',
  'bike rider': '🏍️',
  'auto driver': '🛺',
  'food delivery': '🍔',
  'pet grooming': '🐕',
  'pet walking': '🐾',
  'maid service': '🏠',
  cook: '👨‍🍳',
  babysitter: '👶',
  'barber & saloon service': '💈',
  'salon spa & others (female)': '💇‍♀️',
  'massage therapist': '💆',
  'packers & movers': '📦',
  'ac installation': '❄️',
  'ac repair': '🛠️',
  gardening: '🌱',
  'cctv installation': '📹',
  'scrap collection': '♻️',
  'ambulance booking': '🚑',
};

const KEYWORD_EMOJI: Array<[string, string]> = [
  ['electric', '⚡'],
  ['plumb', '🔧'],
  ['carpent', '🪚'],
  ['paint', '🎨'],
  ['clean', '🧹'],
  ['ac ', '❄️'],
  ['refrigerator', '❄️'],
  ['washing machine', '🫧'],
  ['microwave', '🍳'],
  ['geyser', '♨️'],
  ['chimney', '💨'],
  ['dishwasher', '🍽️'],
  ['tv repair', '📺'],
  ['fan repair', '🌀'],
  ['cooler', '💨'],
  ['inverter', '🔋'],
  ['generator', '⚙️'],
  ['interior', '🏡'],
  ['kitchen', '🍳'],
  ['ceiling', '🏠'],
  ['floor', '🪵'],
  ['wallpaper', '🖼️'],
  ['tile', '🧱'],
  ['curtain', '🪟'],
  ['garden', '🌿'],
  ['lawn', '🌱'],
  ['tree', '🌳'],
  ['plant', '🪴'],
  ['landscape', '🏞️'],
  ['cctv', '📹'],
  ['security', '🔒'],
  ['smart lock', '🔐'],
  ['guard', '🛡️'],
  ['fire', '🔥'],
  ['wifi', '📶'],
  ['network', '🌐'],
  ['automation', '🏠'],
  ['water', '💧'],
  ['borewell', '⛏️'],
  ['pipeline', '🔧'],
  ['construction', '🏗️'],
  ['renovation', '🏗️'],
  ['contractor', '👷'],
  ['roof', '🏠'],
  ['waterproof', '💧'],
  ['furniture', '🛋️'],
  ['wardrobe', '🚪'],
  ['bed ', '🛏️'],
  ['pest', '🦟'],
  ['termite', '🐜'],
  ['cockroach', '🪳'],
  ['mosquito', '🦟'],
  ['rodent', '🐀'],
  ['shift', '🚚'],
  ['moving', '📦'],
  ['maid', '🧹'],
  ['cook', '👨‍🍳'],
  ['baby', '👶'],
  ['elder', '👴'],
  ['patient', '🏥'],
  ['driver', '🚗'],
  ['pet', '🐶'],
  ['laundry', '🧺'],
  ['dry clean', '👔'],
  ['iron', '👕'],
  ['shoe', '👟'],
  ['laptop', '💻'],
  ['computer', '🖥️'],
  ['printer', '🖨️'],
  ['barber', '💈'],
  ['salon', '💇'],
  ['massage', '💆'],
  ['tutor', '📚'],
  ['tuition', '📖'],
  ['class ', '🎓'],
  ['jee', '📝'],
  ['neet', '📝'],
  ['music', '🎵'],
  ['dance', '💃'],
  ['yoga', '🧘'],
  ['gym', '🏋️'],
  ['doctor', '👨‍⚕️'],
  ['physio', '🦴'],
  ['nurs', '💉'],
  ['lab', '🧪'],
  ['blood', '🩸'],
  ['test', '🧪'],
  ['ambulance', '🚑'],
  ['scrap', '♻️'],
  ['gas cylinder', '⛽'],
  ['decoration', '🎉'],
  ['tent', '⛺'],
  ['inspection', '🔍'],
  ['handyman', '🛠️'],
  ['welder', '🔥'],
  ['mason', '🧱'],
  ['door', '🚪'],
  ['window', '🪟'],
  ['delivery', '📦'],
  ['hotel', '🏨'],
  ['restaurant', '🍽️'],
  ['doctor', '👨‍⚕️'],
  ['hospital', '🏥'],
  ['clinic', '🏥'],
  ['shop', '🏪'],
  ['farmer', '🌾'],
  ['lawyer', '⚖️'],
  ['account', '📊'],
  ['developer', '👨‍💻'],
  ['photo', '📷'],
];

export function getProfessionEmoji(label: string, groupEmoji?: string): string {
  const key = normalizeLabel(label);
  if (EXACT_EMOJI[key]) return EXACT_EMOJI[key];

  const emoji = leadingEmoji(label);
  if (emoji) return emoji;

  for (const [keyword, emoji] of KEYWORD_EMOJI) {
    if (key.includes(keyword)) return emoji;
  }

  return groupEmoji || '✨';
}

export function isValidProfessionImage(image?: string | null): boolean {
  if (!image) return false;
  const value = String(image).trim();
  if (!value || value.startsWith('icon:')) return false;
  return value.startsWith('http://') || value.startsWith('https://') || value.startsWith('/');
}
